Repository awe-der/aweder-core, pull requests merged in 2020-05, with the labels that each got.

#6 Correct tiny typo
  docs/pages/Installation/installation.md
Labels: documentation, good first issue

#7 Changed readme file to link to documentation in GH pages
  README.md
Labels: documentation

#8 Create LICENSE
  LICENSE
Labels: documentation

#9 Setup CI with Circle
  .circleci/config.yml
  .env.testing
  .gitignore
  docker-compose.yml
Labels: dependencies

#10 Added readme badges
  README.md
Labels: documentation
