Repository awe-der/aweder-core, pull requests merged in 2020-07, with the labels that each got.

#26 Hotfix/ukr 202 retrospective order fixer
  app/Console/Commands/RetrospectiveOrderQuantitySplitter.php
  app/OrderItem.php
  tests/Unit/Command/OrderQuantitySplitterTest.php
  tests/Unit/Model/OrderItemTest.php
Labels: enhancement

#32 Feature/ukr 215 update registration flow
  .eslintignore
  .gitignore
  __tests__/unit/registration/UrlSlugChecker.spec.js
  __tests__/unit/shared/business_details/MerchantOrderTypes.spec.js
  app/Http/Requests/Admin/BusinessDetailsEditRequest.php
  app/Http/Requests/Registration/BusinessDetailsRequest.php
  app/Inventory.php
  app/Merchant.php
  app/OrderItem.php
  app/Repository/MerchantRepository.php
  app/User.php
  database/factories/Merchant.php
  database/factories/MerchantFactory.php
  database/migrations/2020_07_02_102922_add_table_service_flag.php
  docker-compose.yml
  docker/php/x-debug-off.ini
  public/main.js
  public/main.js.map
  resources/js/bootstrap.js
  resources/js/components/registration/UrlSlugChecker.vue
  resources/js/components/shared/business_details/MerchantOrderTypes.vue
  resources/js/components/svgs/Collection.vue
  resources/js/components/svgs/Delivery.vue
  resources/js/components/svgs/Table.vue
  resources/lang/en/validation.php
  resources/views/admin/details/edit.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/registration/multi-step/business-details/details.blade.php
  resources/views/global/admin.blade.php
  tests/Feature/Admin/Details/PostEditDetailsControllerTest.php
  tests/Feature/Auth/Registration/MultiStep/BusinessDetails/DetailsPostControllerTest.php
  tests/Unit/Model/MerchantTest.php
  tests/Unit/Repository/MerchantRepositoryTest.php
Labels: enhancement

#37 Feature/admin dashboard frontend
  public/main.js
  public/main.js.map
  public/style.css
  resources/js/admin-menu.js
  resources/js/components/shared/business_details/MerchantOrderTypes.vue
  resources/sass/components/avatars/_avatar.scss
  resources/sass/components/components.scss
  resources/sass/global/admin-header/_header.scss
  resources/sass/global/admin-nav/_branding.scss
  resources/sass/global/admin-nav/_menu.scss
  resources/sass/global/admin-nav/_nav.scss
  resources/sass/global/admin-nav/navigation.scss
  resources/sass/global/defaults/_default.scss
  resources/sass/global/global.scss
  resources/sass/global/site-header/_header.scss
  resources/sass/utils/backgrounds/colors/_color.scss
  resources/sass/utils/borders/radii/_mixins.scss
  resources/svgs/arrow-down.svg
  resources/views/global/admin-header.blade.php
  resources/views/global/admin-nav.blade.php
  resources/views/global/admin.blade.php
  resources/views/global/header.blade.php
Labels: enhancement

#35 Feature/ukr 209 add order type check middleware
  app/Http/Kernel.php
  app/Http/Middleware/IsCorrectOrderTypeMiddleware.php
  app/Order.php
  database/migrations/2020_07_07_083207_add_is_table_service_flag_to_order.php
  database/migrations/2020_07_08_090404_add_is_collection_to_order.php
  routes/table_order.php
  routes/take_away.php
  tests/Unit/Middleware/IsCorrectOrderTypeMiddlewareTest.php
  tests/Unit/Model/OrderTest.php
Labels: enhancement

#39 WIP - Feature/new menu layout
  app/Http/Controllers/Store/Menu/ViewController.php
  app/Http/Requests/Registration/BusinessDetailsRequest.php
  public/main.js
  public/main.js.map
  public/style.css
  resources/js/AdminMenu.js
  resources/js/DeliveryCost.js
  resources/js/MerchantRegistration.js
  resources/js/NotificationBanner.js
  resources/js/OpeningTimes.js
  resources/js/OrderFilters.js
  resources/js/SlugChecker.js
  resources/js/StripeElements.js
  resources/js/Timer.js
  resources/js/Upload.js
  resources/js/app.js
  resources/js/bootstrap.js
  resources/sass/components/avatars/_avatar.scss
  resources/sass/components/components.scss
  resources/sass/components/hero/_content.scss
  resources/sass/components/hero/_header.scss
  resources/sass/components/hero/_image.scss
  resources/sass/components/hero/_merchant-delivery.scss
  resources/sass/components/hero/_merchant-times.scss
  resources/sass/components/hero/hero.scss
  resources/sass/components/menu/_cart.scss
  resources/sass/components/menu/_menu-categories.scss
  resources/sass/components/menu/_order.scss
  resources/sass/components/menu/menu.scss
  resources/sass/components/notifications/_default.scss
  resources/sass/components/notifications/notification.scss
  resources/sass/components/openings/_opening.scss
  resources/sass/components/panels/_panel.scss
  resources/sass/components/separator/_separator.scss
  resources/sass/global/admin-header/_header.scss
  resources/sass/global/admin-nav/_branding.scss
  resources/sass/global/admin-nav/_nav.scss
  resources/sass/global/admin-nav/navigation.scss
  resources/sass/global/defaults/_default.scss
  resources/sass/global/site-footer/_footer.scss
  resources/sass/helpers/buttons/_button.scss
  resources/sass/utils/borders/radii/_mixins.scss
  resources/sass/utils/borders/radii/_variables.scss
  resources/sass/utils/colors/_variables.scss
  resources/sass/utils/layouts/display/_variables.scss
  resources/svgs/arrow-down-narrow.svg
  resources/svgs/delivery.svg
  resources/svgs/pinpoint.svg
  resources/views/admin/inventory/index.blade.php
  resources/views/auth/login.blade.php
  resources/views/auth/passwords/confirm.blade.php
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/auth/registration/multi-step/user-details.blade.php
  resources/views/auth/registration/openingHours/index.blade.php
  resources/views/auth/verify.blade.php
  resources/views/home.blade.php
  resources/views/merchant/inventory.blade.php
  resources/views/shared/notification.blade.php
Labels: enhancement

#40 Chore: fix file path for xdebug override unit tests
  .circleci/config.yml
Labels: bug

#41 UPDATE: Documentation update for feature/webpack PR #38
  pages/Installation/installation.md
Labels: documentation

#42 UKR-218 Add Options & Variants
  app/Contract/Repositories/InventoryOptionGroupContract.php
  app/Contract/Repositories/InventoryOptionGroupItemContract.php
  app/Contract/Repositories/InventoryVariantContract.php
  app/Contract/Repositories/OrderContract.php
  app/Inventory.php
  app/InventoryOptionGroup.php
  app/InventoryOptionGroupItem.php
  app/InventoryVariant.php
  app/Order.php
  app/Providers/Repositories/InventoryOptionGroupItemServiceProvider.php
  app/Providers/Repositories/InventoryOptionGroupServiceProvider.php
  app/Providers/Repositories/InventoryVariantServiceProvider.php
  app/Repository/InventoryOptionGroupItemRepository.php
  app/Repository/InventoryOptionGroupRepository.php
  app/Repository/InventoryRepository.php
  app/Repository/InventoryVariantRepository.php
  app/Repository/NormalOpeningHoursRepository.php
  app/Repository/OrderRepository.php
  app/Repository/UserRepository.php
  app/Service/OrderService.php
  app/Service/SearchOrderService.php
  app/User.php
  config/app.php
  database/factories/InventoryOptionGroup.php
  database/factories/InventoryOptionGroupItem.php
  database/factories/InventoryVariant.php
  database/migrations/2020_07_09_105635_create_variants_table.php
  database/migrations/2020_07_09_121207_create_inventory_option_groups_table.php
  database/migrations/2020_07_09_121215_create_inventory_option_group_items_table.php
  tests/TestCase.php
  tests/Unit/Repository/InventoryOptionGroupItemsRepositoryTest.php
  tests/Unit/Repository/InventoryOptionGroupRepositoryTest.php
  tests/Unit/Repository/InventoryRepositoryTest.php
  tests/Unit/Repository/InventoryVariantRepositoryTest.php
Labels: enhancement

#58 UKR 239 (partial) endpoint to add OrderItems to Order
  app/Contract/Repositories/OrderContract.php
  app/Contract/Repositories/OrderItemContract.php
  app/Contract/Service/OrderContract.php
  app/Http/Controllers/Api/Order/AddController.php
  app/Http/Kernel.php
  app/Http/Requests/Api/Order/ApiAddItemToOrderRequest.php
  app/InventoryOptionGroup.php
  app/InventoryOptionGroupItem.php
  app/OrderItem.php
  app/Providers/RouteServiceProvider.php
  app/Repository/OrderItemRepository.php
  app/Repository/OrderRepository.php
  app/Service/OrderService.php
  app/User.php
  database/migrations/2020_07_28_095418_add_option_groups_to_order_item.php
  routes/api.php
  routes/api/v1.php
  tests/Feature/Api/AddToOrderTest.php
  tests/Unit/Repository/OrderRepositoryTest.php
Labels: API, enhancement
